name: SimpleHub
main: Terpz710\SimpleHub\Main
version: 1.0.0
api: 5.0.0
author: Terpz710
description: Simple hubs plugin for Pocketmine-MP
permissions:
  simplehub.sethub:
    description: Allows players to use the /sethub command
    default: op
  simplehub.deletehub:
    description: Allows players to use the /deletehub command
    default: op
  simplehub.hub:
    description: Allows players to use the /hub command
    default: true
